version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile/
    container_name: nginx-container
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"

    volumes:
      - ./www/html/:/var/www/html/
      - ./nginx/:/etc/nginx/conf.d/

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile/
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./www/html/:/var/www/html/

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    volumes:
      - /var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
        - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql